version: '3.8'

services:
 
  db:
    image: mariadb:10.5 
    container_name: prestashop-db
    environment:
      
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'prestashop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'userpass'
    volumes:
      #- ./db_data:/var/lib/mysql
      - ../db_data:/var/lib/mysql
    restart: always

  
  web:
    
    image: prestashop/prestashop:1.7.8-7.4
    container_name: prestashop-web
    depends_on:
      - db 
    ports:
      - "8080:80" 
    environment:
      DB_SERVER: 'db' 
      DB_NAME: 'prestashop'
      DB_USER: 'user'
      DB_PASS: 'userpass'
      PS_DOMAIN: 'localhost:8080' 
    volumes:
      # kody zrodlowe sklepu
      - ../shop_source:/var/www/html
    restart: always

volumes:
  db_data:
