parent: classic
name: classic_child
display_name: szablon u≈ºytkowy
version: 1.0.0
assets:
  use_parent_assets: true
  css:
    all:
      - id: classic_child_custom
        path: assets/css/custom.css
        priority: 2000  # Higher than parent